# This is a basic workflow to help you get started with Actions

name: SYNC

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [main]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Update dir
        run: python update-robailab.py

      - name: Build
        uses: Tiryoh/actions-mkdocs@v0
        with:
          mkdocs_version: "latest" # option
          # mkdocs_version: '1.1' # option
          # requirements: "requirements.txt" # option
          configfile: "mkdocs-robailab.yml" # option

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.PERSONAL_TOKEN }}
          external_repository: robai-lab/hainanu-course-comments
          publish_branch: gh-pages
          publish_dir: ./site

      #- name: Deploy docs
      #  uses: mhausenblas/mkdocs-deploy-gh-pages@master
      #  env:
      #    GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
      #    CUSTOM_DOMAIN: robai-lab.github.io
      #    CONFIG_FILE: mkdocs-robailab.yml
      #    GITHUB_REPOSITORY: robai-lab/hainanu-course-comments
      #    EXTRA_PACKAGES: build-base
      #    REQUIREMENTS: requirements.txt
